language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle/wrapper/
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test "$TRAVIS_TAG" != "" && test $TRAVIS_REPO_SLUG == "avast/metrics" && sh "$TRAVIS_BUILD_DIR/.travis.bintray-credentials.sh" && sbt +publish
